name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Another greeting
        run: echo "Hello, world!"
      - name: run Neural network script
        run: .\NueralNetwork.py
