name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install numpy
        pip install matplotlib
        pip install scrapy
        pip install pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name : run script
      run: |
        # cd /ufc_data 
        ls 
        cd ..
        pwd
        scrapy crawl ufc_stats -o ufc_fighter_stats.csv
        ls
      #        python NueralNetwork.py > output.txt
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: output.txt
        path: Artifacts/output.txt
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}