name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install numpy
        pip install matplotlib
        pip install scrapy
        pip install pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name : run script
      run: |
        pwd
        cd ufcFighterData
        ls 
        pwd
        scrapy crawl fighterdataLink -o fighterDataLink.csv
        ls
        pwd
      #        python NueralNetwork.py > output.txt
    - name: upload fighters stats link
      uses: actions/upload-artifact@v2
      with:
        name: fighterdataLink.csv
        path: /home/runner/work/ProfessorM.M.A/ProfessorM.M.A/ufcFighterData/Artifacts/fighterDataLink.csv
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}